# Generated by Django 3.2.23 on 2024-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240304_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='admissionImage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='admissionTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='delay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departureImage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departureTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='justification',
            field=models.BooleanField(default=False),
        ),
    ]
