# Generated by Django 3.2.23 on 2024-01-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_dni'),
        ('api', '0002_attendance_shedule'),
    ]

    operations = [
    ]
