# Generated by Django 3.2.23 on 2024-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_alter_user_dni_0002_attendance_shedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule',
            new_name='Schedule',
        ),
    ]
