# Generated by Django 3.2.23 on 2024-04-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240306_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justification',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
