# Generated by Django 3.2.23 on 2024-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_alter_user_dni_0002_attendance_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name=([1, 'MANAGEMENT'], [2, 'TEAM_LEADER'], [3, 'COLLABORATOR'])),
            preserve_default=False,
        ),
    ]
