# Generated by Django 3.2.23 on 2024-01-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_shedule_schedule'),
        ('api', '0004_user_role'),
    ]

    operations = [
    ]
