# Generated by Django 3.2.23 on 2024-05-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240502_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='admissionImage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departureImage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'MANAGEMENT'), (2, 'TEAM_LEADER'), (3, 'COLLABORATOR'), (4, 'DEPARTMENT_LEADER')]),
        ),
    ]
