# Generated by Django 3.2.23 on 2024-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240510_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='evidence',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
