# Generated by Django 3.2.23 on 2024-01-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240126_0846'),
        ('api', '0009_auto_20240125_1320'),
    ]

    operations = [
    ]
