# Generated by Django 3.2.23 on 2024-01-31 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240130_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justification',
            name='reason_decline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='justification',
            name='evidence',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='justification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(verbose_name=([1, 'MANAGEMENT'], [2, 'TEAM_LEADER'], [3, 'COLLABORATOR'])),
        ),
    ]
