"""
Django settings for SA_Backend project.

Generated by 'django-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
from dotenv import load_dotenv
load_dotenv()#Leer variables de entorno
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# Llave secreta
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') 

ALLOWED_HOSTS = []
# Configuración del nombre del host para producción
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Settings for X-Frame-Options
X_FRAME_OPTIONS = 'ALLOW-FROM https://consigueventas.netlify.app'

# Settings for Content Security Policy (CSP)
CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'"]
CSP_STYLE_SRC = ["'self'"]
CSP_IMG_SRC = ["'self'", "data:"]
CSP_FRAME_ANCESTORS = ["'self'", "https://consigueventas.netlify.app"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'django_rest_passwordreset', # Para cuando olvidamos la contraseña
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', #Para el CSP
    'csp.middleware.CSPMiddleware',    #Para el CSP
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SA_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SA_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {         
    'default': dj_database_url.config(
         #url de postgressql
        default='postgresql://'+os.environ.get('DB_USER')+':'+os.environ.get('DB_PASSWORD')+'@'+os.environ.get('DB_HOST')+':'+os.environ.get('DB_PORT')+'/'+os.environ.get('DB_NAME'),
        conn_max_age=600
    )
     #'default': {
     #    'ENGINE': 'django.db.backends.postgresql',
     #   'NAME': 'db_sistemaerp',
     #    'USER': 'root',
     #    'PASSWORD': 'root',
     #    'HOST': '165.22.180.66',
     #    'PORT': '5432',
     #    'OPTIONS': {
     #        'options': '-c search_path=public',
     #    },
     #}
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'
TIME_ZONE = 'America/Lima'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -----Configuration para enviar emails----
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Backend de correo electronicos que se usara
EMAIL_PORT = 587  # Puerto para la conexion al servidor de correo electronico
EMAIL_USE_TLS = True  # Proporciona una capa de seguridad en la conexión con el servidor de correo
EMAIL_HOST = 'smtp.gmail.com'  #  Utilización del servidor SMTP de Gmail
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # Usuario de donde se enviaran los correos electronicos
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  # Llave secreta de google 

APPEND_SLASH=False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
AUTH_USER_MODEL = 'api.User' # Indicamos el modelo de authentication para toda la api
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", #Localhost
    "http://127.0.0.1:5173", #Localhost
    "http://165.22.180.66",
    "http://165.22.180.66:5173",
    "https://"+config('URI_CLIENT'), #deployment
    "https://"+config('URI_API'), #deployment
    'https://consigueventas.netlify.app'
]
CORS_ALLOW_CREDENTIALS = True
